# Generated by Django 2.1.4 on 2019-02-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='blog',
            new_name='post',
        ),
        migrations.AddField(
            model_name='group',
            name='picture',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
