# Generated by Django 2.1.4 on 2018-12-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profile pictures'),
        ),
    ]
