# Generated by Django 2.1.4 on 2019-04-01 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notfication_text', models.TextField(default='<django.db.models.fields.related.ForeignKey>', max_length=200)),
                ('generation_time', models.TimeField(auto_now_add=True)),
                ('generation_date', models.DateField(auto_now_add=True)),
                ('notification_seen', models.BooleanField(default=False)),
                ('notification_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
