# Generated by Django 2.1.4 on 2019-04-01 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sharing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuggageSharingAcceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('luggageSharing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sharing.LuggageSharing')),
            ],
        ),
    ]
